spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/cycleDB'
    username: Ashish
    password: welcome
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub
